### PR TITLE
pass region to minio client

### LINKED ISSUE #3: Pass region as config to minio client to support s3 bucket as storage
Hi, first of all thanks for providing these options to use custom cache storage providers! 
I really would like to use this lib with a s3 bucket, but during testing, I got the following error:
image
I think this could be fixed by passing a region to the minio client constructor optionally, which could be retrieved from nx.json or env like the other options.
If I find time, I might open a pull-request in the next days to add this option.

### PR DESCRIPTION
**Pull request by johannesf95**
closes #3

### CODE REVIEW

**Comment by NiklasPor** [comment]
Hi, looks really good to me.  I'll merge it after Christmas 🎅 Thanks for your contribution!

**Comment by NiklasPor** [comment]
Sorry for the huge delay @johannesf95. Looks great. I'll merge & release it.

**Comment by johannesf95** [comment]
@NiklasPor No problem, since I figured out that we are actually using a minio bucket in our company. Since we rolled out your nx remote-cache last week, the pipeline performance increased a lot, because before were trying to persist the nx cache by using gitlab cache, but there you always have to upload/download the whole cache.
But might be still interesting for others, who use s3-bucket actually.

**Comment by NiklasPor** [comment]
Great to hear. Happy that you're actively using it. I actually built this only because someone asked me in one of my other packages about other options besides azure 👀

**Pull request merged**
